/**
 * Server-rendered Coach PDF copy. Keep in sync with calculator PDF labels.
 */
export const PDF_LABELS = Object.freeze({
  fr: Object.freeze({
    mainTitle: 'PLAN ALIMENTAIRE PERSONNALISÉ',
    subtitle: 'Évaluation & Planification Nutritionnelle',
    athlete: 'Athlète', date: 'Date', energyGoal: 'Objectif énergétique', dayType: 'Type de journée',
    training: 'Entraînement', macroRatio: 'Ratio macronutriments', targetCalories: 'Calories cibles',
    targetMacros: 'Macros cibles', bankCalories: 'Calories banque', bankMacros: 'Macros banque',
    hydration: 'Hydratation', portionsSection: 'Portions par repas', dailyTotal: 'Total journée',
    footer: 'Référez-vous au guide des équivalents alimentaires',
    pro: 'Pro', glu: 'Glu', lip: 'Lip', perDay: 'L/j',
    preWorkout: 'Pré-entraînement', postWorkout: 'Post-entraînement',
    timingPre: 'Pré', timingPost: 'Post', eauBase: 'Base auto', eauAdd: 'ajout', eauRule: '1 L / 1000 kcal',
    filenamePrefix: 'Plan', defaultAthlete: 'Athlete',
    coachNotesTitle: 'Notes du coach', macroChartTitle: 'Ratio des nutriments',
    nutrient: 'Nutriment', caloriesRow: 'Calories',
    plannedCalories: 'Total planifié', plannedMacros: 'Macros planifiées',
    varianceLabel: 'Écart planifié vs cible', banqueNote: 'Banque (réf. portions)',
    varianceOrigin: 'Écarts dus aux arrondis (formule / moyennes / repas)',
    restOmittedNote: 'Jour repos non configuré — omis du PDF client',
    reconciliationTitle: 'Réconciliation énergétique',
  }),
  en: Object.freeze({
    mainTitle: 'PERSONALIZED MEAL PLAN',
    subtitle: 'Nutrition Assessment & Planning',
    athlete: 'Athlete', date: 'Date', energyGoal: 'Energy goal', dayType: 'Day type',
    training: 'Training', macroRatio: 'Macronutrient ratio', targetCalories: 'Target calories',
    targetMacros: 'Target macros', bankCalories: 'Bank calories', bankMacros: 'Bank macros',
    hydration: 'Hydration', portionsSection: 'Portions per meal', dailyTotal: 'Daily total',
    footer: 'Refer to the food equivalents guide',
    pro: 'Pro', glu: 'Carbs', lip: 'Fat', perDay: 'L/day',
    preWorkout: 'Pre-workout', postWorkout: 'Post-workout',
    timingPre: 'Pre', timingPost: 'Post', eauBase: 'Auto base', eauAdd: 'added', eauRule: '1 L / 1000 kcal',
    filenamePrefix: 'Plan', defaultAthlete: 'Athlete',
    coachNotesTitle: 'Coach notes', macroChartTitle: 'Nutrient ratio',
    nutrient: 'Nutrient', caloriesRow: 'Calories',
    plannedCalories: 'Planned total', plannedMacros: 'Planned macros',
    varianceLabel: 'Planned vs target variance', banqueNote: 'Bank (portion reference)',
    varianceOrigin: 'Variances from rounding (formula / averages / meals)',
    restOmittedNote: 'Rest day not configured — omitted from client PDF',
    reconciliationTitle: 'Energy reconciliation',
  }),
});
