/**
 * Server-rendered Coach PDF copy. Keep in sync with calculator PDF labels.
 */
export const PDF_LABELS = Object.freeze({
  fr: Object.freeze({
    mainTitle: 'PLAN ALIMENTAIRE PERSONNALISÉ',
    subtitle: 'Évaluation des habitudes & planification alimentaire',
    athlete: 'Athlète', date: 'Date', energyGoal: 'Objectif énergétique', dayType: 'Type de journée',
    training: 'Entraînement', macroRatio: 'Répartition des macronutriments', targetCalories: 'Cible alimentaire (macros arrondies)',
    targetMacros: 'Macros cibles', bankCalories: 'Calories banque', bankMacros: 'Macros banque',
    hydration: 'Cible initiale de liquides', portionsSection: 'Portions par repas', dailyTotal: 'Total journée',
    footer: 'Référez-vous au guide des équivalents alimentaires',
    pro: 'Pro', glu: 'Glu', lip: 'Lip', perDay: 'L/j',
    preWorkout: 'Pré-entraînement', postWorkout: 'Post-entraînement',
    timingPre: 'Pré', timingPost: 'Post', eauBase: 'Base auto', eauAdd: 'ajout', eauRule: '1 L / 1000 kcal',
    filenamePrefix: 'Plan', defaultAthlete: 'Athlete',
    coachNotesTitle: 'Notes du coach', macroChartTitle: 'Répartition des macronutriments',
    nutrient: 'Nutriment', caloriesRow: 'Calories',
    plannedCalories: 'Total planifié', plannedMacros: 'Macros planifiées',
    varianceLabel: 'Écart planifié vs cible', banqueNote: 'Portions sélectionnées (moyennes)',
    varianceOrigin: 'Tolérance coach : ±2 % pour l\'énergie et ±6 % par macro. Les petits écarts proviennent des moyennes et des arrondis.',
    restOmittedNote: 'Jour repos non configuré — omis du PDF client',
    reconciliationTitle: 'Réconciliation énergétique',
    brandBy: 'Préparé par',
    withinTolerance: 'dans la tolérance',
    scopeNotice: 'Structure alimentaire destinée à une personne généralement en santé; elle ne remplace pas un avis médical ou un traitement nutritionnel clinique.',
  }),
  en: Object.freeze({
    mainTitle: 'PERSONALIZED MEAL PLAN',
    subtitle: 'Eating habits assessment & meal planning',
    athlete: 'Athlete', date: 'Date', energyGoal: 'Energy goal', dayType: 'Day type',
    training: 'Training', macroRatio: 'Macronutrient distribution', targetCalories: 'Meal target (rounded macros)',
    targetMacros: 'Target macros', bankCalories: 'Bank calories', bankMacros: 'Bank macros',
    hydration: 'Initial fluid target', portionsSection: 'Portions per meal', dailyTotal: 'Daily total',
    footer: 'Refer to the food equivalents guide',
    pro: 'Pro', glu: 'Carbs', lip: 'Fat', perDay: 'L/day',
    preWorkout: 'Pre-workout', postWorkout: 'Post-workout',
    timingPre: 'Pre', timingPost: 'Post', eauBase: 'Auto base', eauAdd: 'added', eauRule: '1 L / 1000 kcal',
    filenamePrefix: 'Plan', defaultAthlete: 'Athlete',
    coachNotesTitle: 'Coach notes', macroChartTitle: 'Macronutrient distribution',
    nutrient: 'Nutrient', caloriesRow: 'Calories',
    plannedCalories: 'Planned total', plannedMacros: 'Planned macros',
    varianceLabel: 'Planned vs target variance', banqueNote: 'Selected portions (averages)',
    varianceOrigin: 'Coach tolerance: ±2% energy and ±6% per macro. Small variances come from averages and rounding.',
    restOmittedNote: 'Rest day not configured — omitted from client PDF',
    reconciliationTitle: 'Energy reconciliation',
    brandBy: 'Prepared by',
    withinTolerance: 'within tolerance',
    scopeNotice: 'Meal structure intended for a generally healthy person; it does not replace medical advice or clinical nutrition treatment.',
  }),
});
