/** Print CSS derived from the calculator's PDF stylesheet and reconciliation patch. */
export function getPdfStylesCss() {
  return `*{box-sizing:border-box;-webkit-print-color-adjust:exact;print-color-adjust:exact}
body{margin:0;padding:0;background:#fff}.pdf-a4-page{width:794px;height:1123px;padding:24px 28px;font-family:Arial,Helvetica,sans-serif;color:#1e293b;font-size:12px;line-height:1.4;background:#fff;overflow:hidden;position:relative;page-break-after:always}
.pdf-a4-page:last-child{page-break-after:auto}.pdf-header{display:flex;align-items:center;border-bottom:3px solid #3b82f6;padding-bottom:12px;margin-bottom:16px}.pdf-brand-banner{background:#071B41;border-radius:6px;padding:10px 14px;display:inline-flex;align-items:center;margin-right:12px;flex-shrink:0}.pdf-brand-logo{height:40px;width:auto;max-width:180px;object-fit:contain;display:block;filter:brightness(0) invert(1)}
.pdf-title{text-align:center;flex:1}.pdf-title h1{font-size:18px;color:#1e293b;font-weight:800;margin:0 0 4px;letter-spacing:.5px}.pdf-title p{color:#64748b;font-size:10px;margin:0}
.info-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-bottom:12px}.info-table,.pdf-recon table{width:100%;border-collapse:collapse;border:1px solid #e2e8f0;table-layout:fixed}.info-table td,.pdf-recon td{padding:5px 8px;border:1px solid #e2e8f0;font-size:10px;color:#334155;vertical-align:middle;overflow-wrap:anywhere}.info-label{background:#f1f5f9;font-weight:700;width:42%;font-size:9.5px;color:#475569}.val-blue{color:#3b82f6;font-weight:700}.val-cyan{color:#0ea5e9;font-weight:700}
.pdf-recon{margin:0;border:1px solid #cbd5e1;border-radius:6px;overflow:hidden}.pdf-recon-title{background:#071B41;color:#fff;font-size:10px;font-weight:700;padding:6px 10px}.pdf-recon-note{font-size:9px;color:#64748b;padding:6px 8px;background:#f8fafc}.var-ok{color:#0f766e;font-weight:700}.var-warn{color:#b45309;font-weight:700}
.pdf-section{font-size:11px;font-weight:700;color:#1e293b;border-left:4px solid #3b82f6;padding-left:8px;margin:0 0 8px}.meals-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px;align-items:start}.meal-box{margin-bottom:7px;padding:6px 8px;background:#f8fafc;border-left:3px solid #3b82f6;border-radius:4px}.meal-title{font-weight:700;font-size:10.5px;color:#1e293b;margin-bottom:2px}.meal-list{margin:0;padding-left:14px}.meal-list li{margin:1px 0;font-size:10px;color:#475569}
.pdf-page-body{padding-bottom:96px}.pdf-coach-notes{margin:10px 0 8px;padding:10px 12px;background:#fffbeb;border:1px solid #fde68a;border-radius:6px}.pdf-coach-notes-body{font-size:10px;color:#475569;line-height:1.55;white-space:pre-wrap}.pdf-macro-chart{margin:8px 0 10px;padding:10px 12px;border:1px solid #e2e8f0;border-radius:6px;background:#fafafa}.pdf-macro-chart-row{display:flex;align-items:center;justify-content:space-between;gap:16px}.macro-ratio-table{border-collapse:collapse;font-size:9.5px}.macro-ratio-table th,.macro-ratio-table td{border:1px solid #cbd5e1;padding:4px 8px;text-align:center}.macro-ratio-table th{background:#f1f5f9;font-weight:700;color:#475569}.pdf-pie-wrap{display:flex;align-items:center;gap:12px}.pdf-pie-svg{width:120px;height:120px;flex-shrink:0}.pdf-pie-legend{font-size:9.5px;color:#475569;line-height:1.6}.dot{display:inline-block;width:10px;height:10px;border-radius:2px;margin-right:5px;vertical-align:middle}.dot-pro{background:#6366f1}.dot-glu{background:#b91c1c}.dot-lip{background:#fde68a;border:1px solid #d4b86a}.pdf-totals{position:absolute;left:28px;right:28px;bottom:48px;background:#1e293b;color:#fff;border-radius:6px;padding:8px 12px;font-size:10px;font-weight:600;text-align:center}.pdf-footer{position:absolute;left:28px;right:28px;bottom:14px;text-align:center;font-size:9px;color:#94a3b8;border-top:1px solid #e2e8f0;padding-top:6px;line-height:1.35}`;
}
